import { Roboto_Serif } from 'next/font/google'
import '../../src/app/globals.css'

import data from '../../src/data.json'
import NavTop from './Components/NavTop';
import Navbar from './Components/Navbar';
import AboutInstructor from './Components/AboutInstructor';
import CourseSaleInfo from './Components/CourseSaleInfo';
import Testimonials from './Components/Testimonials';

const inter = Roboto_Serif({ subsets: ['latin'] })



export const metadata = {
  title: 'Faith App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavTop banner={data["course"].banner} instructorName={data["instructor"].name} courseTitle={data["course"].title}/>
        <Navbar />
        {children}
        <CourseSaleInfo fees={data["course"]["fee"].amount} currency={data["course"]["fee"].currency} inclusion={data["course"].inclusions}  />
        <AboutInstructor profile_url={data["instructor"].profile_photo} about={data["about_instructor"].html_content} social_medias={data["instructor"]["social_media"]} />
        <Testimonials testimonials={data["testimonials"]}/>
      </body>
    </html>
  )
}
